server:
  servlet:
    context-path: /api
  compression:
    enabled: true
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quartz-mysql?characterEncoding=utf-8
    username: root
    password:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false